### PR TITLE
feat: Cache origins

### PR DESCRIPTION
**Pull request by QuentinMoss**
Add support for origin cache using @hjr3 recommendations in https://github.com/hjr3/soldr/issues/1

### CODE REVIEW

**Comment by hjr3** [comment]
check out https://github.com/QuentinMoss/soldr/pull/6

**Comment by QuentinMoss** [comment]
@hjr3 This is :sparkles:. Thanks for the improvements.

**Comment by QuentinMoss** [comment]
Me right now.

giphy

**Review by hjr3 — APPROVED** [review]

**Comment by hjr3** [comment]
great work on this!

**Pull request merged**
